// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH5xxcqwXqoj_DGmOruB3Tn_MLToGSRh8',
    appId: '1:125055635032:web:cf0d5f2b359ed267d4c42d',
    messagingSenderId: '125055635032',
    projectId: 'tasktaker-33fb3',
    authDomain: 'tasktaker-33fb3.firebaseapp.com',
    storageBucket: 'tasktaker-33fb3.firebasestorage.app',
    measurementId: 'G-WZFQWF9TK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVWLQFogoYvCecfz268sPOraTyWbCOT4',
    appId: '1:125055635032:android:cd40d2e70fe4b1b3d4c42d',
    messagingSenderId: '125055635032',
    projectId: 'tasktaker-33fb3',
    storageBucket: 'tasktaker-33fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeir4pEp4KP7sHvtjRhxM8QzU0Kk8UUYQ',
    appId: '1:125055635032:ios:da73202d1f6b78aad4c42d',
    messagingSenderId: '125055635032',
    projectId: 'tasktaker-33fb3',
    storageBucket: 'tasktaker-33fb3.firebasestorage.app',
    iosBundleId: 'com.example.tasktaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeir4pEp4KP7sHvtjRhxM8QzU0Kk8UUYQ',
    appId: '1:125055635032:ios:da73202d1f6b78aad4c42d',
    messagingSenderId: '125055635032',
    projectId: 'tasktaker-33fb3',
    storageBucket: 'tasktaker-33fb3.firebasestorage.app',
    iosBundleId: 'com.example.tasktaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH5xxcqwXqoj_DGmOruB3Tn_MLToGSRh8',
    appId: '1:125055635032:web:edfad5e1c7c4ca3ed4c42d',
    messagingSenderId: '125055635032',
    projectId: 'tasktaker-33fb3',
    authDomain: 'tasktaker-33fb3.firebaseapp.com',
    storageBucket: 'tasktaker-33fb3.firebasestorage.app',
    measurementId: 'G-VYHMYXZ53X',
  );
}
